/*INSERT TABLA ELE_ASESORES*/

INSERT INTO ELE_ASESORES ( NRO_IDENTIFICACION, EMPRESA, RETIRADO ) VALUES ( 
'31860492', 'Club Vacacional', 'No'); 
INSERT INTO ELE_ASESORES ( NRO_IDENTIFICACION, EMPRESA, RETIRADO ) VALUES ( 
'7554438', 'Club Vacacional', 'No'); 
INSERT INTO ELE_ASESORES ( NRO_IDENTIFICACION, EMPRESA, RETIRADO ) VALUES ( 
'16756594', 'Club Vacacional', 'No'); 
INSERT INTO ELE_ASESORES ( NRO_IDENTIFICACION, EMPRESA, RETIRADO ) VALUES ( 
'31931591', 'Club Vacacional', 'No'); 
INSERT INTO ELE_ASESORES ( NRO_IDENTIFICACION, EMPRESA, RETIRADO ) VALUES ( 
'10080469', 'Club Vacacional', 'No'); 
INSERT INTO ELE_ASESORES ( NRO_IDENTIFICACION, EMPRESA, RETIRADO ) VALUES ( 
'16693558', 'Club Vacacional', 'No'); 
INSERT INTO ELE_ASESORES ( NRO_IDENTIFICACION, EMPRESA, RETIRADO ) VALUES ( 
'16610204', 'Club Vacacional', 'No'); 
INSERT INTO ELE_ASESORES ( NRO_IDENTIFICACION, EMPRESA, RETIRADO ) VALUES ( 
'31467170', 'Club Vacacional', 'No'); 
INSERT INTO ELE_ASESORES ( NRO_IDENTIFICACION, EMPRESA, RETIRADO ) VALUES ( 
'29506498', 'Club Vacacional', 'No'); 
INSERT INTO ELE_ASESORES ( NRO_IDENTIFICACION, EMPRESA, RETIRADO ) VALUES ( 
'6702674', 'Club Vacacional', 'No'); 
INSERT INTO ELE_ASESORES ( NRO_IDENTIFICACION, EMPRESA, RETIRADO ) VALUES ( 
'67027293', 'Club Vacacional', 'No'); 
INSERT INTO ELE_ASESORES ( NRO_IDENTIFICACION, EMPRESA, RETIRADO ) VALUES ( 
'1130613253', 'Club Vacacional', 'No'); 
INSERT INTO ELE_ASESORES ( NRO_IDENTIFICACION, EMPRESA, RETIRADO ) VALUES ( 
'16289759', 'Club Vacacional', 'No'); 
INSERT INTO ELE_ASESORES ( NRO_IDENTIFICACION, EMPRESA, RETIRADO ) VALUES ( 
'1144134919', 'Club Vacacional', 'No'); 
INSERT INTO ELE_ASESORES ( NRO_IDENTIFICACION, EMPRESA, RETIRADO ) VALUES ( 
'67028549', 'Club Vacacional', 'No'); 
INSERT INTO ELE_ASESORES ( NRO_IDENTIFICACION, EMPRESA, RETIRADO ) VALUES ( 
'14983245', 'Club Vacacional', 'No'); 
COMMIT;


/*INSERT TABLA ELE_P_PARAMETROS*/

INSERT INTO ELE_P_PARAMETROS ( CODIGO_PARAMETRO, NOMBRE_PARAMETRO, VALOR_PARAMETRO, CODIGO_ESTADO,
TIPO_PARAMETRO ) VALUES ( 
7, 'Fecha Inicio de Admision e Inadmision', '25-01-2010 12:00:00 am', 1, 'PARAMETRO'); 
INSERT INTO ELE_P_PARAMETROS ( CODIGO_PARAMETRO, NOMBRE_PARAMETRO, VALOR_PARAMETRO, CODIGO_ESTADO,
TIPO_PARAMETRO ) VALUES ( 
8, 'Fecha Final de Admision e Inadmision', '27-01-2010 12:00:00 am', 1, 'PARAMETRO'); 
INSERT INTO ELE_P_PARAMETROS ( CODIGO_PARAMETRO, NOMBRE_PARAMETRO, VALOR_PARAMETRO, CODIGO_ESTADO,
TIPO_PARAMETRO ) VALUES ( 
9, 'Fecha Inicio de Admision por saneamiento', '28-01-2010 12:00:00 am', 1, 'PARAMETRO'); 
INSERT INTO ELE_P_PARAMETROS ( CODIGO_PARAMETRO, NOMBRE_PARAMETRO, VALOR_PARAMETRO, CODIGO_ESTADO,
TIPO_PARAMETRO ) VALUES ( 
10, 'Fecha Final de Admision por saneamiento', '28-01-2010 5:00:00 pm', 1, 'PARAMETRO'); 
INSERT INTO ELE_P_PARAMETROS ( CODIGO_PARAMETRO, NOMBRE_PARAMETRO, VALOR_PARAMETRO, CODIGO_ESTADO,
TIPO_PARAMETRO ) VALUES ( 
11, 'Fecha Inicio de Admision por Apelación', '10-02-2010 12:00:00 am', 1, 'PARAMETRO'); 
INSERT INTO ELE_P_PARAMETROS ( CODIGO_PARAMETRO, NOMBRE_PARAMETRO, VALOR_PARAMETRO, CODIGO_ESTADO,
TIPO_PARAMETRO ) VALUES ( 
12, 'Fecha Final de Admision por Apelación', '10-02-2010 6:00:00 pm', 1, 'PARAMETRO'); 
INSERT INTO ELE_P_PARAMETROS ( CODIGO_PARAMETRO, NOMBRE_PARAMETRO, VALOR_PARAMETRO, CODIGO_ESTADO,
TIPO_PARAMETRO ) VALUES ( 
13, 'Fecha Inicio de Saneamiento', '27-01-2010 12:00:00 am', 1, 'PARAMETRO'); 
INSERT INTO ELE_P_PARAMETROS ( CODIGO_PARAMETRO, NOMBRE_PARAMETRO, VALOR_PARAMETRO, CODIGO_ESTADO,
TIPO_PARAMETRO ) VALUES ( 
14, 'Fecha Final de Saneamiento', '28-01-2010 5:00:00 pm', 1, 'PARAMETRO'); 
INSERT INTO ELE_P_PARAMETROS ( CODIGO_PARAMETRO, NOMBRE_PARAMETRO, VALOR_PARAMETRO, CODIGO_ESTADO,
TIPO_PARAMETRO ) VALUES ( 
1, 'Web Service Profile Manager ', 'http://cdplin13.intracoomeva.com.co:9092/WsProfile/services/Caas?wsdl'
, 1, 'PARAMETRO'); 
INSERT INTO ELE_P_PARAMETROS ( CODIGO_PARAMETRO, NOMBRE_PARAMETRO, VALOR_PARAMETRO, CODIGO_ESTADO,
TIPO_PARAMETRO ) VALUES ( 
2, 'Nombre Aplicación ', 'Elecciones', 1, 'PARAMETRO'); 
INSERT INTO ELE_P_PARAMETROS ( CODIGO_PARAMETRO, NOMBRE_PARAMETRO, VALOR_PARAMETRO, CODIGO_ESTADO,
TIPO_PARAMETRO ) VALUES ( 
3, 'Numero Aplicación Directorio Activo  ', '1', 1, 'PARAMETRO'); 
INSERT INTO ELE_P_PARAMETROS ( CODIGO_PARAMETRO, NOMBRE_PARAMETRO, VALOR_PARAMETRO, CODIGO_ESTADO,
TIPO_PARAMETRO ) VALUES ( 
4, 'Numero Aplicación Ldap ', '2', 1, 'PARAMETRO'); 
INSERT INTO ELE_P_PARAMETROS ( CODIGO_PARAMETRO, NOMBRE_PARAMETRO, VALOR_PARAMETRO, CODIGO_ESTADO,
TIPO_PARAMETRO ) VALUES ( 
5, 'Fecha Inicio de Inscripcion', '21-01-2010 12:00:00 am', 1, 'PARAMETRO'); 
INSERT INTO ELE_P_PARAMETROS ( CODIGO_PARAMETRO, NOMBRE_PARAMETRO, VALOR_PARAMETRO, CODIGO_ESTADO,
TIPO_PARAMETRO ) VALUES ( 
6, 'Fecha Final de Inscripcion', '23-01-2010 12:00:00 am', 1, 'PARAMETRO'); 
COMMIT;


/*INSERT TABLA ELE_ZONAS*/

INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'03', 19, 'ZE01', 'Bogotá'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'04', 1, 'ZE01', 'Boyacá'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'01', 2, 'ZE04', 'Armenia'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'02', 7, 'ZE03', 'Barranquilla'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'05', 2, 'ZE05', 'Bucaramanga'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'06', 1, 'ZE02', 'Buenaventura'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'07', 1, 'ZE02', 'Buga'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'08', 1, 'ZE04', 'Cartago'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'09', 2, 'ZE03', 'Cartagena'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'10', 2, 'ZE05', 'Cúcuta'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'11', 2, 'ZE05', 'Envigado'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'20', 2, 'ZE04', 'Pereira'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'22', 18, 'ZE02', 'Santiago de Cali'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'12', 1, 'ZE02', 'Florencia'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'13', 2, 'ZE02', 'Ibagué'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'14', 2, 'ZE04', 'Manizales'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'15', 13, 'ZE05', 'Medellín'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'16', 2, 'ZE05', 'Montería'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'17', 1, 'ZE02', 'Neiva'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'18', 3, 'ZE06', 'Palmira'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'19', 1, 'ZE02', 'Pasto'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'21', 3, 'ZE02', 'Popayán'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'23', 1, 'ZE03', 'Santa Marta'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'24', 2, 'ZE02', 'Tulúa'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'25', 1, 'ZE05', 'Urabá'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'26', 1, 'ZE03', 'Valledupar'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'27', 1, 'ZE01', 'Yopal'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'ZE01', 1, 'Si', 'Zona Especial Bogotá'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'ZE02', 1, 'Si', 'Zona Especial Cali'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'ZE03', 1, 'Si', 'Zona Especial Caribe'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'ZE04', 1, 'Si', 'Zona Especial Eje Cafetero'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'ZE05', 1, 'Si', 'Zona Especial Medellín'); 
INSERT INTO ELE_ZONAS ( COD_ZONA, MAX_PRINCIPALES, ZON_ESPECIAL,
NOM_ZONA ) VALUES ( 
'ZE06', 1, 'Si', 'Zona Especial Palmira'); 
COMMIT;


/*INSERT TABLA ELE_ZONAS_FINANCIERO*/

INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'AR', '01', 'Armenia'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'BQ', '02', 'Barranquilla'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'SI', '02', 'Sincelejo'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'BO', '03', 'Bogotá'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'VI', '03', 'Villavicencio'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'SO', '04', 'Sogamoso'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'TJ', '04', 'Tunja'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'DT', '04', 'Duitama'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'BU', '05', 'Bucaramanga'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'BR', '05', 'Barrancabermeja'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'BV', '06', 'Buenaventura'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'BG', '07', 'Buga'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'CT', '08', 'Cartago'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'CG', '09', 'Cartagena'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'CU', '10', 'Cúcuta'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'PA', '10', 'Pamplona'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'EV', '11', 'Envigado'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'PE', '20', 'Pereira'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'CL', '22', 'Cali'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'FL', '12', 'Florencia'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'IB', '13', 'Ibagué'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'MN', '14', 'Manizales'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'MD', '15', 'Medellín'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'QB', '15', 'Quibdo'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'MT', '16', 'Montería'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'NE', '17', 'Neiva'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'PL', '18', 'Palmira'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'PS', '19', 'Pasto'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'IP', '19', 'Ipiales'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'PO', '21', 'Popayán'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'SN', '23', 'Santa Marta'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'TL', '24', 'Tulúa'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'ZR', '24', 'Zarzal'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'UR', '25', 'Urabá'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'VA', '26', 'Valledupar'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'YO', '27', 'Yopal'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'MS', '02', 'Mushaisha'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'RA', '02', 'Rioacha'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'CH', '03', 'Chia'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'SH', '03', 'Soacha'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'IT', '11', 'Itagui'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'BE', '15', 'Bello'); 
INSERT INTO ELE_ZONAS_FINANCIERO ( COD_ZONA_FIN, COD_ZONA_ELEC,
NOM_ZONA_FIN ) VALUES ( 
'RN', '15', 'Rionegro'); 
COMMIT;


/*INSERT TABLA ELE_SUBCOMISION*/

INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'7505398', '01'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'1359038', '01'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'8259842', '01'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'5198280', '01'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'14986377', '01'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'4400869', '01'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'13893505', '05'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'32798728', '05'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'13350401', '05'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'37935821', '05'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'37938876', '05'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'27788882', '05'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'17137015', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'32637643', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'6490252', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'6155759', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'41777665', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'17073646', '03'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'41726192', '03'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'19362706', '03'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'19118584', '03'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'11331506', '03'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'37791215', '05'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'25264052', '05'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'13346333', '05'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'28475443', '05'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'13807526', '05'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'16470159', '06'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'6149756', '06'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'31378574', '06'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'6160729', '06'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'71598109', '06'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'29223742', '06'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'6182120', '07'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'2891388', '07'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'29283014', '07'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'38860230', '07'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'14883186', '07'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'29278502', '07'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'45760121', '09'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'73168045', '09'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'45715855', '09'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'33152673', '09'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'22407897', '09'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'45765439', '09'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'16208225', '08'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'1410534', '08'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'29392651', '08'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'38984629', '08'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'31395479', '08'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'31408522', '08'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'13509955', '10'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'37367365', '10'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'60321313', '10'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'27887136', '10'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'60305339', '10'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'37246362', '10'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'46665471', '04'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'4266282', '04'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'8210109', '11'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'24292186', '11'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'8347305', '11'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'15422705', '11'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'46871057', '11'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'70071661', '11'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'13832544', '12'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'17627821', '12'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'19203745', '12'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'31968313', '12'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'7543256', '12'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'17631948', '12'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'38216912', '13'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'38253352', '13'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'14227229', '13'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'2852158', '13'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'28514868', '13'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'38233653', '13'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'6771691', '19'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'27396299', '19'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'27381497', '19'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'40038823', '19'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'37002454', '19'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'87718182', '19'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'24306924', '14'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'30280220', '14'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'10243838', '14'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'16050521', '14'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'4482757', '14'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'24305288', '14'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'533130', '15'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'32314502', '15'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'8245130', '15'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'21830405', '15'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'32498417', '15'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'10779201', '16'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'50916839', '16'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'1067836558', '16'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'79946508', '16'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'43972286', '16'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'50890460', '16'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'19388575', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'13810875', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'8666549', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'70050873', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'84036823', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'79230140', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'7698305', '17'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'6756328', '17'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'36152425', '17'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'26607483', '17'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'12105292', '17'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'93359929', '17'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'6380654', '18'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'31154088', '18'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'16269813', '18'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'16266510', '18'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'16236711', '18'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'16257988', '18'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'13347957', '10'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'60338366', '10'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'5475579', '10'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'88031085', '10'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'60254435', '10'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'12993814', '19'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'30715603', '19'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'30707731', '19'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'12980135', '19'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'5199176', '19'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'27076471', '19'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'10219479', '20'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'17139642', '20'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'4507535', '20'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'10105879', '20'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'4513392', '20'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'51763284', '20'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'4610688', '21'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'4606376', '21'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'4606338', '21'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'6744388', '21'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'881824', '21'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'98365', '21'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'26284439', '15'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'11830007', '15'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'26256473', '15'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'26259852', '15'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'30102103', '15'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'40912287', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'60322451', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'56053843', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'41585042', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'73090411', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'19496929', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'85451659', '23'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'41713834', '23'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'57461810', '23'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'72165987', '23'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'79982362', '23'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'37001985', '22'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'19112871', '22'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'16701779', '22'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'51784090', '22'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'34511654', '22'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'10884785', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'92540999', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'8860805', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'92532738', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'51691069', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'64928939', '02'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'9395696', '04'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'33448759', '04'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'9531232', '04'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'9513392', '04'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'4038357', '04'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'9524460', '04'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'14434900', '24'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'16349761', '24'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'29866111', '24'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'14936184', '24'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'6454824', '24'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'31197460', '24'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'1147237', '04'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'6764484', '04'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'40037260', '04'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'4129233', '04'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'23265828', '04'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'3347280', '25'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'10268994', '25'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'70519099', '25'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'29462179', '25'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'42895464', '25'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'77030326', '26'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'9262834', '26'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'36710609', '26'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'8530213', '26'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'42490379', '26'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'7417494', '26'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'65749355', '03'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'86087053', '03'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'17168179', '03'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'38981135', '03'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'67023902', '03'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'47434781', '27'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'19097685', '27'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'19221383', '27'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'9523324', '27'); 
INSERT INTO ELE_SUBCOMISION ( NRO_IDENTIFICACION, SUBCOMISIONZONA ) VALUES ( 
'93291201', '27'); 
COMMIT;