INSERT INTO ELECLIB.ASOCIADO(  "NRO_IDENTIFICACION",
        "PRIMER_NOMBRE",
        "SEGUNDO_NOMBRE",
        "PRIMER_APELLIDO",
        "SEGUNDO_APELLIDO",
        "EDAD",
        "PROFESION",
        "EMAIL",
        "ANTIGUEDAD",
        "MEDIO_VOTACION",
        "HABIL",
        "RETIRADO",
        "FECHA_INGRESO",
        "FECHA_CARGUE",
        "ZONA",
        "REGIONAL",
        "OFICINA",
        "FECHA_RETIRO",
        "OTROS_ESTUDIOS" ) 
VALUES('12345','Prueba1','Prueba1','Prueba1','Prueba1',1,'Ingenieria Prueba','Prueba@Prueba.com',3,'Audio','H','R','2009-12-01','2009-12-25','CALI','CALI','NACIONAL','2009-12-25','Prueba Tecnica');
        
 INSERT INTO ELECLIB.ASOCIADO(  "NRO_IDENTIFICACION",
        "PRIMER_NOMBRE",
        "SEGUNDO_NOMBRE",
        "PRIMER_APELLIDO",
        "SEGUNDO_APELLIDO",
        "EDAD",
        "PROFESION",
        "EMAIL",
        "ANTIGUEDAD",
        "MEDIO_VOTACION",
        "HABIL",
        "RETIRADO",
        "FECHA_INGRESO",
        "FECHA_CARGUE",
         "ZONA",
        "REGIONAL",
        "OFICINA",
        "FECHA_RETIRO",
        "OTROS_ESTUDIOS" ) 
VALUES('45678','Prueba2','Prueba2','Prueba2','Prueba2',1,'Ingenieria Prueba2','Prueba2@Prueba.com',1,'Audio2','IH','R','2009-12-01','2009-12-25','CALI','CALI','NACIONAL','2009-12-25','Prueba2 Tecnica');

 INSERT INTO ELECLIB.ASOCIADO(  "NRO_IDENTIFICACION",
        "PRIMER_NOMBRE",
        "SEGUNDO_NOMBRE",
        "PRIMER_APELLIDO",
        "SEGUNDO_APELLIDO",
        "EDAD",
        "PROFESION",
        "EMAIL",
        "ANTIGUEDAD",
        "MEDIO_VOTACION",
        "HABIL",
        "RETIRADO",
        "FECHA_INGRESO",
        "FECHA_CARGUE",
         "ZONA",
        "REGIONAL",
        "OFICINA",
        "FECHA_RETIRO",
        "OTROS_ESTUDIOS" ) 
VALUES('1','Prueba2','Prueba2','Prueba2','Prueba2',1,'Ingenieria Prueba2','Prueba2@Prueba.com',1,'Audio2','IH','R','2009-12-01','2009-12-25','CALI','CALI','NACIONAL','2009-12-25','Prueba2 Tecnica');
 INSERT INTO ELECLIB.ASOCIADO(  "NRO_IDENTIFICACION",
        "PRIMER_NOMBRE",
        "SEGUNDO_NOMBRE",
        "PRIMER_APELLIDO",
        "SEGUNDO_APELLIDO",
        "EDAD",
        "PROFESION",
        "EMAIL",
        "ANTIGUEDAD",
        "MEDIO_VOTACION",
        "HABIL",
        "RETIRADO",
        "FECHA_INGRESO",
        "FECHA_CARGUE",
         "ZONA",
        "REGIONAL",
        "OFICINA",
        "FECHA_RETIRO",
        "OTROS_ESTUDIOS" ) 
VALUES('2','Prueba2','Prueba2','Prueba2','Prueba2',1,'Ingenieria Prueba2','Prueba2@Prueba.com',1,'Audio2','IH','R','2009-12-01','2009-12-25','CALI','CALI','NACIONAL','2009-12-25','Prueba2 Tecnica');
 INSERT INTO ELECLIB.ASOCIADO(  "NRO_IDENTIFICACION",
        "PRIMER_NOMBRE",
        "SEGUNDO_NOMBRE",
        "PRIMER_APELLIDO",
        "SEGUNDO_APELLIDO",
        "EDAD",
        "PROFESION",
        "EMAIL",
        "ANTIGUEDAD",
        "MEDIO_VOTACION",
        "HABIL",
        "RETIRADO",
        "FECHA_INGRESO",
        "FECHA_CARGUE",
         "ZONA",
        "REGIONAL",
        "OFICINA",
        "FECHA_RETIRO",
        "OTROS_ESTUDIOS" ) 
VALUES('3','Prueba2','Prueba2','Prueba2','Prueba2',1,'Ingenieria Prueba2','Prueba2@Prueba.com',1,'Audio2','H','R','2009-12-01','2009-12-25','CALI','CALI','NACIONAL','2009-12-25','Prueba2 Tecnica');
 INSERT INTO ELECLIB.ASOCIADO(  "NRO_IDENTIFICACION",
        "PRIMER_NOMBRE",
        "SEGUNDO_NOMBRE",
        "PRIMER_APELLIDO",
        "SEGUNDO_APELLIDO",
        "EDAD",
        "PROFESION",
        "EMAIL",
        "ANTIGUEDAD",
        "MEDIO_VOTACION",
        "HABIL",
        "RETIRADO",
        "FECHA_INGRESO",
        "FECHA_CARGUE",
         "ZONA",
        "REGIONAL",
        "OFICINA",
        "FECHA_RETIRO",
        "OTROS_ESTUDIOS" ) 
VALUES('4','Prueba2','Prueba2','Prueba2','Prueba2',1,'Ingenieria Prueba2','Prueba2@Prueba.com',1,'Audio2','H','R','2009-12-01','2009-12-25','CALI','CALI','NACIONAL','2009-12-25','Prueba2 Tecnica');
 INSERT INTO ELECLIB.ASOCIADO(  "NRO_IDENTIFICACION",
        "PRIMER_NOMBRE",
        "SEGUNDO_NOMBRE",
        "PRIMER_APELLIDO",
        "SEGUNDO_APELLIDO",
        "EDAD",
        "PROFESION",
        "EMAIL",
        "ANTIGUEDAD",
        "MEDIO_VOTACION",
        "HABIL",
        "RETIRADO",
        "FECHA_INGRESO",
        "FECHA_CARGUE",
         "ZONA",
        "REGIONAL",
        "OFICINA",
        "FECHA_RETIRO",
        "OTROS_ESTUDIOS" ) 
VALUES('5','Prueba2','Prueba2','Prueba2','Prueba2',1,'Ingenieria Prueba2','Prueba2@Prueba.com',1,'Audio2','H','R','2009-12-01','2009-12-25','CALI','CALI','NACIONAL','2009-12-25','Prueba2 Tecnica');
INSERT INTO ELECLIB.ASOCIADO(  "NRO_IDENTIFICACION",
        "PRIMER_NOMBRE",
        "SEGUNDO_NOMBRE",
        "PRIMER_APELLIDO",
        "SEGUNDO_APELLIDO",
        "EDAD",
        "PROFESION",
        "EMAIL",
        "ANTIGUEDAD",
        "MEDIO_VOTACION",
        "HABIL",
        "RETIRADO",
        "FECHA_INGRESO",
        "FECHA_CARGUE",
         "ZONA",
        "REGIONAL",
        "OFICINA",
        "FECHA_RETIRO",
        "OTROS_ESTUDIOS" ) 
VALUES('6','Prueba2','Prueba2','Prueba2','Prueba2',1,'Ingenieria Prueba2','Prueba2@Prueba.com',1,'Audio2','H','R','2009-12-01','2009-12-25','CALI','CALI','NACIONAL','2009-12-25','Prueba2 Tecnica');
INSERT INTO ELECLIB.ASOCIADO(  "NRO_IDENTIFICACION",
        "PRIMER_NOMBRE",
        "SEGUNDO_NOMBRE",
        "PRIMER_APELLIDO",
        "SEGUNDO_APELLIDO",
        "EDAD",
        "PROFESION",
        "EMAIL",
        "ANTIGUEDAD",
        "MEDIO_VOTACION",
        "HABIL",
        "RETIRADO",
        "FECHA_INGRESO",
        "FECHA_CARGUE",
         "ZONA",
        "REGIONAL",
        "OFICINA",
        "FECHA_RETIRO",
        "OTROS_ESTUDIOS" ) 
VALUES('7','Prueba2','Prueba2','Prueba2','Prueba2',1,'Ingenieria Prueba2','Prueba2@Prueba.com',1,'Audio2','H','R','2009-12-01','2009-12-25','CALI','CALI','NACIONAL','2009-12-25','Prueba2 Tecnica');
INSERT INTO ELECLIB.INHABILIDADES(
        "COD_INHABILIDAD",
        "CONCEPTO_INHABILIDAD" )
VALUES
        ('P','El Asociado no cumple con la antiguedad');
        
        
 INSERT INTO ELECLIB.ASOHAB(NRO_IDENTIFICACION,COD_INHABILIDAD) VALUES('45678','P');
 
    INSERT INTO "ELECCION"."ELE_P_PARAMETROS"( "CODIGO_PARAMETRO", "NOMBRE_PARAMETRO" ,  "VALOR_PARAMETRO" ,  "CODIGO_ESTADO",  "TIPO_PARAMETRO")
    VALUES (1,'Web Service Profile Manager ','http://cdplin13.intracoomeva.com.co:9092/WsProfile/services/Caas?wsdl',1,'PARAMETRO');
    INSERT INTO "ELECCION"."ELE_P_PARAMETROS"( "CODIGO_PARAMETRO", "NOMBRE_PARAMETRO" ,  "VALOR_PARAMETRO" ,  "CODIGO_ESTADO",  "TIPO_PARAMETRO")
    VALUES (2,'Nombre Aplicación ','Elecciones',1,'PARAMETRO');
    INSERT INTO "ELECCION"."ELE_P_PARAMETROS"( "CODIGO_PARAMETRO", "NOMBRE_PARAMETRO" ,  "VALOR_PARAMETRO" ,  "CODIGO_ESTADO",  "TIPO_PARAMETRO")
    VALUES (3,'Numero Aplicación Directorio Activo  ','1',1,'PARAMETRO');
    INSERT INTO "ELECCION"."ELE_P_PARAMETROS"( "CODIGO_PARAMETRO", "NOMBRE_PARAMETRO" ,  "VALOR_PARAMETRO" ,  "CODIGO_ESTADO",  "TIPO_PARAMETRO")
    VALUES (4,'Numero Aplicación Ldap ','2',1,'PARAMETRO');
    INSERT INTO "ELECCION"."ELE_P_PARAMETROS"( "CODIGO_PARAMETRO", "NOMBRE_PARAMETRO" ,  "VALOR_PARAMETRO" ,  "CODIGO_ESTADO",  "TIPO_PARAMETRO")
    VALUES (5,'Fecha Inicio de Inscripcion','18-12-2009 12:00:00 am',1,'PARAMETRO');
    INSERT INTO "ELECCION"."ELE_P_PARAMETROS"( "CODIGO_PARAMETRO", "NOMBRE_PARAMETRO" ,  "VALOR_PARAMETRO" ,  "CODIGO_ESTADO",  "TIPO_PARAMETRO")
    VALUES (6,'Fecha Final de Inscripcion','22-01-2010 12:00:00 pm',1,'PARAMETRO');
    INSERT INTO "ELECCION"."ELE_P_PARAMETROS"( "CODIGO_PARAMETRO", "NOMBRE_PARAMETRO" ,  "VALOR_PARAMETRO" ,  "CODIGO_ESTADO",  "TIPO_PARAMETRO")
    VALUES (7,'Fecha Inicio de Admision e Inadmision','25-01-2010 12:00:00 am',1,'PARAMETRO');
    INSERT INTO "ELECCION"."ELE_P_PARAMETROS"( "CODIGO_PARAMETRO", "NOMBRE_PARAMETRO" ,  "VALOR_PARAMETRO" ,  "CODIGO_ESTADO",  "TIPO_PARAMETRO")
    VALUES (8,'Fecha Final de Admision e Inadmision','27-01-2010 12:00:00 am',1,'PARAMETRO');
    INSERT INTO "ELECCION"."ELE_P_PARAMETROS"( "CODIGO_PARAMETRO", "NOMBRE_PARAMETRO" ,  "VALOR_PARAMETRO" ,  "CODIGO_ESTADO",  "TIPO_PARAMETRO")
    VALUES (9,'Fecha Inicio de Admision por saneamiento','28-01-2010 12:00:00 am',1,'PARAMETRO');
    INSERT INTO "ELECCION"."ELE_P_PARAMETROS"( "CODIGO_PARAMETRO", "NOMBRE_PARAMETRO" ,  "VALOR_PARAMETRO" ,  "CODIGO_ESTADO",  "TIPO_PARAMETRO")
    VALUES (10,'Fecha Final de Admision por saneamiento','28-01-2010 5:00:00 pm',1,'PARAMETRO');
     INSERT INTO "ELECCION"."ELE_P_PARAMETROS"( "CODIGO_PARAMETRO", "NOMBRE_PARAMETRO" ,  "VALOR_PARAMETRO" ,  "CODIGO_ESTADO",  "TIPO_PARAMETRO")
    VALUES (11,'Fecha Inicio de Admision por Apelación','08-02-2010 12:00:00 am',1,'PARAMETRO');
    INSERT INTO "ELECCION"."ELE_P_PARAMETROS"( "CODIGO_PARAMETRO", "NOMBRE_PARAMETRO" ,  "VALOR_PARAMETRO" ,  "CODIGO_ESTADO",  "TIPO_PARAMETRO")
    VALUES (12,'Fecha Final de Admision por Apelación','10-02-2010 12:00:00 am',1,'PARAMETRO');
      INSERT INTO "ELECCION"."ELE_P_PARAMETROS"( "CODIGO_PARAMETRO", "NOMBRE_PARAMETRO" ,  "VALOR_PARAMETRO" ,  "CODIGO_ESTADO",  "TIPO_PARAMETRO")
    VALUES (13,'Fecha Inicio de Saneamiento','27-01-2010 12:00:00 am',1,'PARAMETRO');
    INSERT INTO "ELECCION"."ELE_P_PARAMETROS"( "CODIGO_PARAMETRO", "NOMBRE_PARAMETRO" ,  "VALOR_PARAMETRO" ,  "CODIGO_ESTADO",  "TIPO_PARAMETRO")
    VALUES (14,'Fecha Final de Saneamiento','10-02-2010 12:00:00 am',1,'PARAMETRO');
    
    
     INSERT INTO ELECCION.ELE_LOG("CONSECUTIVO", "NRO_CABO_PLANCHA", "TIPOTRANS", "FECHA", "USUARIO", "DESCRIPCION") VALUES(1,'101','tt6', '2009-12-01','yyyy-mm-dd'),'RACO7755','Numeración'); 
	 INSERT INTO ELECCION.ELE_LOG("CONSECUTIVO", "NRO_CABO_PLANCHA", "TIPOTRANS", "FECHA", "USUARIO", "DESCRIPCION") VALUES(2,'100','tt3', '2009-12-02','yyyy-mm-dd'),'MANOLITO','Orden');
	     
    
    insert into "ELECCION"."ELE_ZONAS_FINANCIERO" ( 
        "COD_ZONA_FIN",
        "COD_ZONA_ELEC",
        "NOM_ZONA_FIN" ) values ('CL','CL','Cali');
 
  
  INSERT INTO ELECCION.ELE_PLANCHAS("NRO_CAB_PLANCHA","COD_ZONA","FECHA_INSCRIPCION","ESTADO","NRO_PLANCHA","DESC_ESTADO")
  VALUES('5963128','02','2009-12-02','yyyy-mm-dd'),'Inscrita',NULL,NULL);
  
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('01',10,'Si','Armenia');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('02',10,'Si','Barranquilla');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('03',10,'Si','Bogota');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('04',10,'Si','Boyacá');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('05',10,'Si','Bucaramanga');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('06',10,'Si','Buenaventura');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('07',10,'Si','Buga');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('08',10,'Si','Cartago');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('09',10,'Si','Cartagena');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('10',10,'Si','Cucuta_Pamplona');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('11',10,'Si','Envigado');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('12',10,'Si','Florencia');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('13',10,'Si','Ibagué');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('14',10,'Si','Manizales');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('15',10,'Si','Medellín_Quibdo');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('16',10,'Si','Montería');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('17',10,'Si','Neiva');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('18',10,'Si','Palmira');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('19',10,'Si','Pasto');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('20',10,'No','Pereira');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('21',10,'Si','Popayán');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('22',10,'Si','Santiago de Cali');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('23',10,'Si','Santa Marta');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('24',10,'Si','Tulúa');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('25',10,'Si','Urabá');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('26',10,'Si','Valledupar');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('27',10,'Si','Yopal');

INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('AR','01','Armenia');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('BQ','02','Barranquilla');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('SI','02','Sincelejo');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('MS','02','Mushaisha');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('RA','02','Rioacha');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('BO','03','Bogota');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('VI','03','Villavicencio');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('CH','03','Chia');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('SH','03','Soacha');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('SO','04','Sogamoso');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('TJ','04','Tunja');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('DT','04','Duitama');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('BU','05','Bucaramanga');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('BR','05','Barrancabermeja');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('BV','06','Buenaventura');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('BG','07','Buga');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('CT','08','Cartago');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('CG','09','Cartagena');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('CU','10','Cúcuta');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('PA','10','Pamplona');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('EV','11','Envigado');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('IT','11','Itagui');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('FL','12','Florencia');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('IB','13','Ibagué');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('MN','14','Manizales');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('MD','15','Medellín');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('QB','15','Quibdo');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('BE','15','Bello');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('RN','15','Rionegro');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('MT','16','Montería');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('NE','17','Neiva');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('PL','18','Palmira');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('PS','19','Pasto');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('IP','19','Ipiales');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('PE','20','Pereira');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('PO','21','Popayán');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('CL','22','Cali');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('SN','23','Santa Marta');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('TL','24','Tulúa');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('ZR','24','Zarzal');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('UR','25','Urabá');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('VA','26','Valledupar');
INSERT INTO ELECCION.ELE_ZONAS_FINANCIERO("COD_ZONA_FIN","COD_ZONA_ELEC","NOM_ZONA_FIN") values('YO','27','Yopal');

INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('ZE01',19,'Si','Zona Especial Bogota');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('ZE02',19,'Si','Zona Especial Cali');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('ZE03',6,'Si','Zona Especial Caribe');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('ZE04',2,'Si','Zona Especial Eje Cafetero');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('ZE05',13,'Si','Zona Especial Medellin');
INSERT INTO ELECCION. ELE_ZONAS ("COD_ZONA","MAX_PRINCIPALES","ZON_ESPECIAL","NOM_ZONA") values('ZE06',3,'Si','Zona Especial Palmira'); 

DELETE FROM ELECCION.ELE_CAB_PLANCHA WHERE NRO_IDENTIFICACION  = 72209956;
DELETE FROM ELECCION.ELE_CAB_PLANCHA WHERE NRO_IDENTIFICACION  = 41391494;

DELETE FROM ELECCION.ELE_PLANCHAS WHERE NRO_CAB_PLANCHA  = 72209956;
DELETE FROM ELECCION.ELE_PLANCHAS WHERE NRO_CAB_PLANCHA  = 10515930;
DELETE FROM ELECCION.ELE_PLANCHAS WHERE NRO_CAB_PLANCHA  = 41391494;

DELETE FROM ELECCION.ELE_SUPLENTES WHERE NRO_SU_IDENTIFICACION  = 41391494;

DELETE FROM ELECCION.ELE_PRINCIPALES WHERE NRO_PRI_IDENTIFICACION  = 41391494;

DELETE FROM ELECCION.ELE_EXPERIENCIA_LABORAL WHERE NRO_IDENTIFICACION  = 41391494;

INSERT INTO ELECCION.ELE_ASESORES("NRO_IDENTIFICACION","EMPRESA","RETIRADO") VALUES('31860492','Club Vacacional','No');
INSERT INTO ELECCION.ELE_ASESORES("NRO_IDENTIFICACION","EMPRESA","RETIRADO") VALUES('7554438','Club Vacacional','No');
INSERT INTO ELECCION.ELE_ASESORES("NRO_IDENTIFICACION","EMPRESA","RETIRADO") VALUES('16756594','Club Vacacional','No');
INSERT INTO ELECCION.ELE_ASESORES("NRO_IDENTIFICACION","EMPRESA","RETIRADO") VALUES('31931591','Club Vacacional','No');
INSERT INTO ELECCION.ELE_ASESORES("NRO_IDENTIFICACION","EMPRESA","RETIRADO") VALUES('10080469','Club Vacacional','No');
INSERT INTO ELECCION.ELE_ASESORES("NRO_IDENTIFICACION","EMPRESA","RETIRADO") VALUES('16693558','Club Vacacional','No');
INSERT INTO ELECCION.ELE_ASESORES("NRO_IDENTIFICACION","EMPRESA","RETIRADO") VALUES('16610204','Club Vacacional','No');
INSERT INTO ELECCION.ELE_ASESORES("NRO_IDENTIFICACION","EMPRESA","RETIRADO") VALUES('31467170','Club Vacacional','No');
INSERT INTO ELECCION.ELE_ASESORES("NRO_IDENTIFICACION","EMPRESA","RETIRADO") VALUES('29506498','Club Vacacional','No');
INSERT INTO ELECCION.ELE_ASESORES("NRO_IDENTIFICACION","EMPRESA","RETIRADO") VALUES('6702674','Club Vacacional','No');
INSERT INTO ELECCION.ELE_ASESORES("NRO_IDENTIFICACION","EMPRESA","RETIRADO") VALUES('67027293','Club Vacacional','No');
INSERT INTO ELECCION.ELE_ASESORES("NRO_IDENTIFICACION","EMPRESA","RETIRADO") VALUES('1130613253','Club Vacacional','No');
INSERT INTO ELECCION.ELE_ASESORES("NRO_IDENTIFICACION","EMPRESA","RETIRADO") VALUES('16289759','Club Vacacional','No');
INSERT INTO ELECCION.ELE_ASESORES("NRO_IDENTIFICACION","EMPRESA","RETIRADO") VALUES('1144134919','Club Vacacional','No');
INSERT INTO ELECCION.ELE_ASESORES("NRO_IDENTIFICACION","EMPRESA","RETIRADO") VALUES('67028549','Club Vacacional','No');
INSERT INTO ELECCION.ELE_ASESORES("NRO_IDENTIFICACION","EMPRESA","RETIRADO") VALUES('14983245','Club Vacacional','No');

INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('16470159','06');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('6149756','06');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('31378574','06');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('6160729','06');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('71598109','06');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('29223742','06');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('6182120','07');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('2891388','07');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('29283014','07');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('29278502','07');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('13832544','12');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('17627821','12');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('19203745','12');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('31968313','12');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('7543256','12');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('17631948','12');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('38216912','13');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('38253352','13');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('14227229','13');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('2852158','13');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('28514868','13');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('38233653','13');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('7698305','17');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('6756328','17');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('36152425','17');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('26607483','17');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('12105292','17');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('93359929','17');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('30715603','19');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('30707731','19');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('5199176','19');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('27076471','19');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('4610688','21');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('4606376','21');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('4606338','21');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('6744388','21');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('881824','21');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('98365','21');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('14434900','24');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('16354358','24');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('29866111','24');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('14936184','24');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('6454824','24');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('31197460','24');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('17073646','03');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('41726192','03');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('19362706','03');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('19118584','03');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('11331506','03');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('9395696','04');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('33448759','04');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('9531232','04');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('9513392','04');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('4038357','04');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('9524460','04');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('1147237','04');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('6764484','04');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('4129233','04');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('23265828','04');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('47434781','27');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('19097685','27');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('93291201','27');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('533130','15');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('32314502','15');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('8245130','15');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('8237939','15');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('8301849','15');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('32498417','15');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('8210109','11');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('24292186','11');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('8347305','11');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('15422705','11');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('46871057','11');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('70071661','11');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('37791215','05');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('25264052','05');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('13346333','05');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('28475443','05');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('13807526','05');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('13509955','10');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('60321313','10');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('37247362','10');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('13347957','10');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('60338366','10');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('5475579','10');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('88031085','10');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('60254435','10');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('10779201','16');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('50916839','16');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('1067836558','16');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('79946508','16');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('13893505','05');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('32798728','05');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('13350401','05');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('37935821','05');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('37938876','05');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('27788882','05');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('3347280','25');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('10268994','25');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('70519099','25');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('29462179','25');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('42895464','25');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('26284439','15');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('11830007','15');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('26259852','15');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('30102103','15');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('26256473','15');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('17137015','02');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('32637643','02');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('6490252','02');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('6155759','02');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('41777665','02');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('45760121','09');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('73168045','09');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('45715855','09');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('33152673','09');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('22407897','09');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('45765439','09');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('85451659','23');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('41713834','23');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('57461810','23');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('72165987','23');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('79982362','23');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('10884785','02');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('92540999','02');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('8860805','02');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('92532738','02');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('64928939','02');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('77030326','26');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('36710609','26');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('8530213','26');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('42490379','26');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('7417494','26');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('16208225','08');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('1410534','08');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('29392651','08');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('38984629','08');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('31395479','08');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('31408522','08');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('24306924','14');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('30280220','14');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('10243838','14');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('16050521','14');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('4482757','14');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('24305288','14');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('10219479','20');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('17139642','20');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('4507535','20');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('10105879','20');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('4513392','20');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('51763284','20');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('6380654','18');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('31154088','18');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('16266510','18');
INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('16236711','18');

--SubComision
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('33815535','01');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('72257130','02');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('32609203','02');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('30646426','02');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('92525073','02');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('19135806','03');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('86067548','03');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('46372440','04');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('40038239','04');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('60402805','05');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('28403413','06');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('31379924','06');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('31792018','07');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('31428711','08');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('45508247','09');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('60386463','10');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('60265451','10');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('43598703','11');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('55059079','12');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('28948463','13');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('30287241','14');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('32142152','15');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('35600663','15');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('52620170','16');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('55170127','17');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('94326730','18');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('59831959','19');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('38874148','20');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('34563185','21');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('31880408','22');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('32788039','23');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('16365774','24');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('29362824','25');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('49740696','26');
INSERT INTO ELECCION.ELE_SUBCOMISION(NRO_IDENTIFICACION,SUBCOMISIONZONA) VALUES('46366817','27');



INSERT INTO ELECCION.ELE_SUBCOMISION("NRO_IDENTIFICACION","SUBCOMISIONZONA") VALUES('94315337','22');

ALTER TABLE ELE_CAB_PLANCHA MODIFY("PRIMER_NOMBRE" VARCHAR2(100));
ALTER TABLE ELE_CAB_PLANCHA MODIFY("SEGUNDO_NOMBRE" VARCHAR2(100));
ALTER TABLE ELE_CAB_PLANCHA MODIFY("PRIMER_APELLIDO" VARCHAR2(100));
ALTER TABLE ELE_CAB_PLANCHA MODIFY("SEGUNDO_APELLIDO" VARCHAR2(100));

ALTER TABLE ELE_PRINCIPALES MODIFY("PRIMER_NOMBRE" VARCHAR2(100));
ALTER TABLE ELE_PRINCIPALES MODIFY("SEGUNDO_NOMBRE" VARCHAR2(100));
ALTER TABLE ELE_PRINCIPALES MODIFY("PRIMER_APELLIDO" VARCHAR2(100));
ALTER TABLE ELE_PRINCIPALES MODIFY("SEGUNDO_APELLIDO" VARCHAR2(100));

ALTER TABLE ELE_SUPLENTES MODIFY("PRIMER_NOMBRE" VARCHAR2(100));
ALTER TABLE ELE_SUPLENTES MODIFY("SEGUNDO_NOMBRE" VARCHAR2(100));
ALTER TABLE ELE_SUPLENTES MODIFY("PRIMER_APELLIDO" VARCHAR2(100));
ALTER TABLE ELE_SUPLENTES MODIFY("SEGUNDO_APELLIDO" VARCHAR2(100)); 

ALTER TABLE ELE_LOG MODIFY("USUARIO" VARCHAR2(100));

DELETE FROM ELECCION.ELE_SUPLENTES WHERE NRO_CAB_PLANCHA = 34971368;
DELETE FROM ELECCION.ELE_PRINCIPALES WHERE NRO_CAB_PLANCHA = 34971368;
DELETE FROM ELECCION.ELE_EXPERIENCIA_LABORAL WHERE NRO_IDENTIFICACION = 34971368;
DELETE FROM ELECCION.ELE_CAB_PLANCHA WHERE NRO_IDENTIFICACION = 34971368;
DELETE FROM ELECCION.ELE_PLANCHAS WHERE NRO_CAB_PLANCHA = 34971368;
DELETE FROM ELECCION.ELE_INHABILIDADES WHERE NRO_IDENTIFICACION = 34971368;

delete from ELE_PLANCHAS where NRO_CAB_PLANCHA = 19298028;
delete from ELE_SUPLENTES where NRO_PRI_IDENTIFICACION = 19298028;
delete from ELE_PRINCIPALES where NRO_PRI_IDENTIFICACION = 19298028;
delete from ELE_INHABILIDADES where NRO_IDENTIFICACION = 19298028;
delete from ELE_EXPERIENCIA_LABORAL where NRO_IDENTIFICACION = 19298028;
delete from ELE_CAB_PLANCHA where NRO_IDENTIFICACION = 19298028;

DELETE FROM ELECCION.ELE_SUPLENTES;
DELETE FROM ELECCION.ELE_PRINCIPALES;
DELETE FROM ELECCION.ELE_EXPERIENCIA_LABORAL;
DELETE FROM ELECCION.ELE_CAB_PLANCHA;
DELETE FROM ELECCION.ELE_PLANCHAS;
DELETE FROM ELECCION.ELE_INHABILIDADES;


